### ISSUE TITLE
delete eks cluster

### ISSUE THREAD

**Issue by lukashov-org** [redradrat/aws-iam-operator#15]
Hello, we, company Yad2 from Israel, want to use your project "aws-iam-operator" for infrastructure as a code. We have two problems for this: when you delete the cluster, all users and groups and everything that we have created are also deleted. The second problem is the inability to delete an object after receiving an error. Maybe you have a solution? thanks.

**Comment by redradrat** [comment]
Can you elaborate on "delete the cluster"? How exactly are you proceeding here. Cleaning out all resources first? Because if the iam operator is shut down, the deletion should not be triggered afaik.

For 2) yeah I know. Basically the deletions is triggered, it somehow fails, but then the deletion workflow is not re-triggered ever. Basically I'll have to look into recovering problems there... Can you give a concrete example here?

**Comment by redradrat** [comment]
Closing this as no further info for now.
